name: Trigger test 2 (should work)
on:
  push:
    branches:
      - main
    paths:
      - 'docs/**'

jobs:
  say_hello:
    runs-on: ubuntu-latest
    steps:
      - name: Hello World
        run: echo "Hello, World!"
